### ISSUE TITLE
Have you encountered the problem that some tiff files cannot be read with PIL?

### ISSUE THREAD

**Issue by ranck626** [bai-xiaosheng/SAR-CLIP#2]
def __getitem__(self, item):
        data = self.img[item]
        # data = Image.open(self.img[item])
        # a = len(img.split())
        # data = np.array(Image.open(self.img[item]))
        label = self.labels[item]
        return data, label
Why did you comment out the code for reading images?
In the OpenSARShip dataset, there are some tiff files that cannot be read. 😫

**Comment by bai-xiaosheng** [comment]
The code to open the image is located in model.models.preprocess.
 I did not encounter the problem that the tiff file could not be opened because I was using the MSTAR data set that had been converted to image format.

![屏幕截图 2024-08-22 182831](https://github.com/user-attachments/assets/ac68675f-dae5-4e5b-9efb-a96022754c02)

**Comment by ranck626** [comment]
THANKS YOU!!!
